import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { EmotionRegistry } from "@/components/ui/emotion-registry";
import { TopNavBar } from "@/components/ui/top-nav-bar/top-nav-bar";
import { Separator } from "@chakra-ui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      suppressHydrationWarning
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className='flex min-h-full flex-col'>
        <EmotionRegistry>
          <Provider>
            <TopNavBar />
            <Separator />
            {children}
          </Provider>
        </EmotionRegistry>
      </body>
    </html>
  );
}
